// <auto-generated />
namespace TodoListAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edittodoitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edittodoitem));
        
        string IMigrationMetadata.Id
        {
            get { return "202108051216057_edit-todo-item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
